services:
  mongo_for_test_technique:
    image: mongo:latest
    container_name: mongo_for_test_technique
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo_express_for_test_technique:
    image: mongo-express:latest
    container_name: mongo_express_for_test_technique
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo_for_test_technique
    ports:
      - "8081:8081"
    depends_on:
      - mongo_for_test_technique
      
volumes:
  mongo_data:
    driver: local
