services:
  mongo_for_test_technique:
    image: mongo:latest
    container_name: mongo_for_test_technique
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    container_name: test_technique
    environment:
      MONGO_URI: mongodb://admin:admin@mongo_for_test_technique:27017/nest?authSource=admin
    ports:
      - '3000:3000' 
    depends_on:
      - mongo_for_test_technique

volumes:
  mongo_data:
    driver: local
